name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install azure-functions==1.15.0

    # This step is important - it mimics what VS Code does
    - name: Prepare function app for deployment
      run: |
        mkdir -p .python_packages/lib/site-packages
        pip install --target=".python_packages/lib/site-packages" -r requirements.txt
        
    # Set environment variables similar to your local setup
    - name: Set environment variables
      run: |
        echo "AZURE_FUNCTIONS_ENVIRONMENT=Production" >> $GITHUB_ENV
        echo "PYTHON_ENABLE_WORKER_EXTENSIONS=1" >> $GITHUB_ENV
        
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'test-ocp8'
        slot-name: 'production'
        package: '.'
        respect-funcignore: true
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true