name: Deploy Python Azure Function App - ocp8azurefunctions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies (optional check)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Optional testing step
      # - name: Run tests
      #   run: |
      #     source venv/bin/activate
      #     pytest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7629F27ACFCB4CB8A07B437DAE6E987B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8338839F66F74F588FC12E4AB0B50785 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0073983C5A0C484B826A70AC19010FBA }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'ocp8azurefunctions'
          slot-name: 'Production'
          package: '.'  # Let Azure handle packaging and deploying properly
